### ISSUE TITLE
FixedFormatter

### ISSUE THREAD

**Issue by jaresoles** [chrisruis/MutTui#12]
This error keeps appearing:

/usr/local/lib/python3.10/dist-packages/MutTui/plot_spectrum.py:102: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([""] * len(mutations))

**Comment by chrisruis** [comment]
Thanks @jaresoles I think this is a warning from matplotlib, I've now updated the plotting functions to remove it. It wasn't an error so any previous output files shouldn't be affected
