### ISSUE TITLE
'run_treetime_mugration' is not defined

### ISSUE THREAD

**Issue by evandiego83** [chrisruis/MutTui#13]
Hello Christopher, 

I seem to be having an error while trying to label trees using a csv file. My command is 

`MutTui run -a alignment.fasta -t tree.nwk -l all_taxon_labels.csv --all_sites -o out --rna` and my tips label file has a header as in csv format.

I get the error message:

`treetime reconstruction complete. Importing alignment from reconstruction and tree
Alignment and tree imported. Reconstructing spectrum
Traceback (most recent call last):
  File "/usr/local/bin/MutTui", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MutTui/__main__.py", line 70, in main
    args.func(args)
  File "/usr/local/lib/python3.11/site-packages/MutTui/muttui.py", line 247, in muttui
    run_treetime_mugration(args.output_dir + "annotated_tree.nexus", args.output_dir + "all_taxon_labels.csv", args.output_dir)
    ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'run_treetime_mugration' is not defined
`

Can you please help as the code is not running as described.

Thanks you
Evan

**Comment by chrisruis** [comment]
Thanks @evandiego83 It looks like the run_treetime_mugration function wasn't being imported properly. I've now updated that and it works ok on a test dataset. Please let me know if you have any more issues
