### ISSUE TITLE
creating vcf file from alignment

### ISSUE THREAD

**Issue by DorothyTamYiLing** [chrisruis/MutTui#15]
Hi Chris,

I have a fasta alignment file created by aligning reads to a reference genome using snippy, and I would like to generate a vcf file from there for the conversion step input. Normally I would use snp-sites, but do you have a recommendation that is the most compatible with MutTui? (preferably not to re-map reads again)

Thanks,
Dorothy

**Comment by chrisruis** [comment]
Hi Dorothy,

I think it will depend on whether you'd expect recombination in the dataset. If not, snp-sites will work well to extract the variable sites alignment and vcf to convert alignment positions to genome positions. If there's likely recombination in there, I'd recommend gubbins as that will give you a variable sites alignment and the vcf after screening for recombination.

Chris

**Comment by chrisruis** [comment]
Hi Dorothy,

I'll close this issue for now but please feel free to reopen if you have any further questions.

Chris
